In [1]:
import pandas as pd
import numpy as np
data1 = pd.read_csv('种植业除语法树.csv')

In [4]:
data1

,Unnamed: 0,date,code,open,high,low,close,preclose,volume,amount,...,function_ratio,n_ratio,nine_stroke,no_text,sen_per_para,sum_para,word_max,word_mean,word_phrase,word_var
0,0,2018-01-02,713,6.88,6.91,6.84,6.89,6.88,2102630,1.446595e+07,...,0.178138,0.508772,0.509236,0.439024,9.272727,22.0,24.0,3.607676,0.495575,5.19383
1,1,2018-01-03,713,6.91,6.95,6.87,6.94,6.89,2178901,1.507106e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
2,2,2018-01-04,713,6.97,6.98,6.91,6.92,6.94,2092990,1.451126e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
3,3,2018-01-05,713,6.94,7.01,6.92,6.99,6.92,2130098,1.483042e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
4,4,2018-01-08,713,6.95,7.04,6.88,6.97,6.99,4232971,2.946746e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13865,13865,2020-12-25,603336,11.32,11.38,10.50,10.63,11.60,26885315,2.910912e+08,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
13866,13866,2020-12-28,603336,10.56,10.94,10.41,10.78,10.63,15859301,1.700210e+08,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
13867,13867,2020-12-29,603336,10.70,10.78,10.45,10.51,10.78,14677042,1.552971e+08,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
13868,13868,2020-12-30,603336,10.60,10.72,10.20,10.48,10.51,11480935,1.206785e+08,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000
13869,13869,2020-12-31,603336,10.37,10.75,10.34,10.57,10.48,11585998,1.221771e+08,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.00000